name: 'Setup CNCF SOPS'
description: 'Install a specific version of the sops binary.'
inputs: 
  version:
    description: 'Version of SOPS'
    required: true
    default: 'latest'
outputs:
  sops-path:
    description: 'Path to the cached sops binary'
branding:
  icon: 'unlock'
  color: 'gray-dark'
runs:
  using: 'node20'
  main: 'lib/run.js'
  
